server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://10.8.210.11:3306/checkout_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1q2w3e
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

ecommerce:
  order:
    jwtSecret: whateversecret
    jwtExpireMinutes: 30

logging:
  level:
    org:
      springframework:
        security: DEBUG
    hibernate: DEBUG
    root: info
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS,Asia/Shanghai} %X{requestId}-%X{userId} %highlight(%-5level) %logger{36} : %m%n%wEx"
    file: "%date{yyyy-MM-dd HH:mm:ss.SSS,Asia/Shanghai} %X{requestId}-%X{userId} %highlight(%-5level) %logger{36} : %m%n%wEx"
  path: /data/application/restaurant/logs/
  file: /data/application/restaurant/logs/restaurant-service.log
